---
- name: install filebeat
  ansible.builtin.apt:
    deb: "https://ftp.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.14-amd64.deb"
    state: present
    
- name: Copy Filebeat configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: '0644'
  notify:
    - Restart Filebeat

- name: Make sure a service is running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: filebeat

- name: Index patterns
  ansible.builtin.command:
        sudo filebeat setup -e  