---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Create www directory
  ansible.builtin.file:
    path: /var/www/{{ domain }}
    state: directory
    mode: '0775'

- name: Delete default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Copy custom config
  ansible.builtin.copy:
    src: ./config/nginx.conf
    dest: /etc/nginx/
  notify: restart nginx

 name: Copy nginx site.conf
 ansible.builtin.template:
   src: site.conf.j2
   dest: /etc/nginx/sites-enabled/{{ domain }}
   owner: root
   group: root
   mode: '0644'
 notify: restart nginx

- name: Copy website
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/{{ domain }}
        
