---
- name: Copy website files to server
  synchronize:
    src: /path/to/your/local/website
    dest: /var/www/html
  delegate_to: localhost

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Enable Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Configure Nginx for website
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ domain }}
  notify:
    - Reload Nginx

- name: Create symbolic link to enable site
  file:
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    state: link
  notify:
    - Reload Nginx
