---
- name: Configure Zabbix
  hosts: zabbix
  become: yes
  vars:   
    mysql_password: 'mysecretpass'
  roles:
    - zabbix

- name: Configure Elastic
  hosts: elastic
  become: yes
  roles:
    - elastic

- name: Configure Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana

- name: Configure Web Servers
  hosts: web
  become: yes
  roles:
    - web
    - filebeat
 
- name: zabbix agent
  hosts: 
    - web
    - elastic
    - kibana
    - bastion
  become: yes
  roles:
    - zabbix_agent